services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expõe a porta 3000
    depends_on:
      - redis # Garante que o Redis seja iniciado antes da aplicação
    environment:
      - REDIS_URL=redis://redis:6379 # Define a URL do Redis no ambiente da aplicação
    volumes:
      - .:/app # Monta o diretório atual no container (útil para desenvolvimento)

  redis:
    image: redis:alpine # Usa a imagem oficial do Redis
    ports:
      - "6379:6379" # A porta do Redis pode ser fixa, pois o Redis escutará apenas na rede interna do Docker
